float:
  any:
  - base_args: ['@metric']
    constructor: Qdrant
    disabled: false
    docker_tag: ann-benchmarks-qdrant
    module: ann_benchmarks.algorithms.qdrant
    name: qdrant_quant_none
    run_groups:
      normal_32:
        args: [
          ['none'], #quantization
          [ 8, 16 ], #m
          [ 32 ], #ef_construct
        ]
        query_args: [
          [10, 20, 30, 40, 80, 120, 200, 300, 400], #hnsw_ef
          [True, False], # re-score
        ]
      normal_64:
        args: [
          ['none'], #quantization
          [ 8, 16, 32 ], #m
          [ 64 ], #ef_construct
        ]
        query_args: [
          [10, 20, 30, 40, 80, 120, 200, 300, 400], #hnsw_ef
          [True, False], # re-score
        ]
      normal_96:
        args: [
          ['none'], #quantization
          [ 8, 16, 32, 48 ], #m
          [ 96 ], #ef_construct
        ]
        query_args: [
          [10, 20, 30, 40, 80, 120, 200, 300, 400], #hnsw_ef
          [True, False], # re-score
        ]
      normal_192:
        args: [
          ['none'], #quantization
          [ 8, 16, 32, 48, 96 ], #m
          [ 192 ], #ef_construct
        ]
        query_args: [
          [10, 20, 30, 40, 80, 120, 200, 300, 400], #hnsw_ef
          [True, False], # re-score
        ]
      normal_256:
        args: [
          ['none'], #quantization
          [ 8, 16, 32, 48, 96 ], #m
          [ 256 ], #ef_construct
        ]
        query_args: [
          [10, 20, 30, 40, 80, 120, 200, 300, 400], #hnsw_ef
          [True, False], # re-score
        ]
  - base_args: ['@metric']
    constructor: Qdrant
    disabled: false
    docker_tag: ann-benchmarks-qdrant
    module: ann_benchmarks.algorithms.qdrant
    name: qdrant_quant_scalar
    run_groups:
      normal_32:
        args: [
          ['scalar'], #quantization
          [ 8, 16 ], #m
          [ 32 ], #ef_construct
        ]
        query_args: [
          [10, 20, 30, 40, 80, 120, 200, 300, 400], #hnsw_ef
          [True, False], # re-score
        ]
      normal_64:
        args: [
          ['scalar'], #quantization
          [ 8, 16, 32 ], #m
          [ 64 ], #ef_construct
        ]
        query_args: [
          [10, 20, 30, 40, 80, 120, 200, 300, 400], #hnsw_ef
          [True, False], # re-score
        ]
      normal_96:
        args: [
          ['scalar'], #quantization
          [ 8, 16, 32, 48 ], #m
          [ 96 ], #ef_construct
        ]
        query_args: [
          [10, 20, 30, 40, 80, 120, 200, 300, 400], #hnsw_ef
          [True, False], # re-score
        ]
      normal_192:
        args: [
          ['scalar'], #quantization
          [ 8, 16, 32, 48, 96 ], #m
          [ 192 ], #ef_construct
        ]
        query_args: [
          [10, 20, 30, 40, 80, 120, 200, 300, 400], #hnsw_ef
          [True, False], # re-score
        ]
      normal_256:
        args: [
          ['scalar'], #quantization
          [ 8, 16, 32, 48, 96 ], #m
          [ 256 ], #ef_construct
        ]
        query_args: [
          [10, 20, 30, 40, 80, 120, 200, 300, 400], #hnsw_ef
          [True, False], # re-score
        ]
  - base_args: ['@metric']
    constructor: Qdrant
    disabled: false
    docker_tag: ann-benchmarks-qdrant
    module: ann_benchmarks.algorithms.qdrant
    name: qdrant_quant_binary
    run_groups:
      normal_32:
        args: [
          ['binary'], #quantization
          [ 8, 16 ], #m
          [ 32 ], #ef_construct
        ]
        query_args: [
          [10, 20, 30, 40, 80, 120, 200, 300, 400], #hnsw_ef
          [True, False], # re-score
        ]
      normal_64:
        args: [
          ['binary'], #quantization
          [ 8, 16, 32 ], #m
          [ 64 ], #ef_construct
        ]
        query_args: [
          [10, 20, 30, 40, 80, 120, 200, 300, 400], #hnsw_ef
          [True, False], # re-score
        ]
      normal_96:
        args: [
          ['binary'], #quantization
          [ 8, 16, 32, 48 ], #m
          [ 96 ], #ef_construct
        ]
        query_args: [
          [10, 20, 30, 40, 80, 120, 200, 300, 400], #hnsw_ef
          [True, False], # re-score
        ]
      normal_192:
        args: [
          ['binary'], #quantization
          [ 8, 16, 32, 48, 96 ], #m
          [ 192 ], #ef_construct
        ]
        query_args: [
          [10, 20, 30, 40, 80, 120, 200, 300, 400], #hnsw_ef
          [True, False], # re-score
        ]
      normal_256:
        args: [
          ['binary'], #quantization
          [ 8, 16, 32, 48, 96 ], #m
          [ 256 ], #ef_construct
        ]
        query_args: [
          [10, 20, 30, 40, 80, 120, 200, 300, 400], #hnsw_ef
          [True, False], # re-score
        ]
  - base_args: ['@metric']
    constructor: Qdrant
    disabled: false
    docker_tag: ann-benchmarks-qdrant
    module: ann_benchmarks.algorithms.qdrant
    name: qdrant_quant_none2
    run_groups:
      normal_192:
        args: [
          ['none'], #quantization
          [ 8, 16, 32, 48, 96 ], #m
          [ 192 ], #ef_construct
        ]
        query_args: [
          [10, 20, 30, 40, 80, 120, 200, 300, 400], #hnsw_ef
          [True, False], # re-score
        ]
