float:
  any:
  - base_args: ['@metric']
    constructor: Heatwave
    disabled: false
    docker_tag: ann-benchmarks-heatwave
    module: ann_benchmarks.algorithms.heatwave
    name: heatwave
    run_groups:
      normal:
        arg_groups: [{txt: 'test', M: [4]}]
        args: {}
        query_args: [[10]]

